### PR TITLE
Added codeclimate code-quality metrics

### PR DESCRIPTION
**Pull request by iainbeeston**
As an anal and lazy developer
I want a code quality badge
So that I can quickly assess if Treehouse.js is well written

### CODE REVIEW

**Comment by markevans** [comment]
not sure what I think about these types of metrics but let's see anyway!

**Comment by iainbeeston** [comment]
You'll love it!

I think you also need to turn on travis from travis-ci.org, for it to
receive the git hooks.

**Comment by markevans** [comment]
aye tis done (travis).
codeclimate showed 0.3 at first and I wasn't sure if that was good or not. turned out it was terrible haha.
Turned off semicolon-checking (coz I don't do semicolons) and removed the compiled file and went up to 4.0 yay! (phew)

**Comment by iainbeeston** [comment]
It just uses JSHint, so you can tell it not to care:

http://docs.codeclimate.com/article/241-can-i-customize-how-javascript-linting-is-performed

**Pull request merged**
